application: i2a-solutions
version: 12
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /site_media
  static_dir: site_media

- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: django
  version: 1.2

